import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { FaculteCombobox } from "@/components/ui/faculteCombonox";

export const metadata: Metadata = {
    title: "Bibliotheque Numérique UCBukavu",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SidebarProvider className="dark">
            <AppSidebar />
            <main className="w-full bg-[#0b0b0b] text-gray-300">
                <div className="flex items-center py-3">
                    <SidebarTrigger className="text-gray-200" />
                </div>
                {children}
            </main>
        </SidebarProvider>
    );
}
